require 'spec_helper'
require 'faker/name'
# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AutoresController do

  before(:each) do
    stub_sign_in
  end

  # This should return the minimal set of attributes required to create a valid
  # Autore. As you add validations to Autore, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => Faker::Name.name } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AutoresController. Be sure to keep this updated too.
  let(:valid_session) {  }

  describe "GET index" do
    it "allows authenticated access" do
      autore = FactoryGirl.create(:autore)
      get :index
      assigns(:autores).should eq([autore])
    end

    it "blocks unauthenticated access" do
      get :index, nil,stub_sign_in(nil)
      response.should redirect_to(new_user_session_path)
    end

  end

  describe "GET show" do
    it "assigns the requested autore as @autore" do
      autore = Autore.create! valid_attributes
      get :show, {:id => autore.to_param}, valid_session
      assigns(:autore).should eq(autore)
    end
  end

  describe "GET new" do
    it "assigns a new autore as @autore" do
      get :new, {}, valid_session
      assigns(:autore).should be_a_new(Autore)
    end
  end

  describe "GET edit" do
    it "assigns the requested autore as @autore" do
      autore = Autore.create! valid_attributes
      get :edit, {:id => autore.to_param}, valid_session
      assigns(:autore).should eq(autore)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Autore" do
        expect {
          post :create, {:autore => valid_attributes}, valid_session
        }.to change(Autore, :count).by(1)
      end

      it "assigns a newly created autore as @autore" do
        post :create, {:autore => valid_attributes}, valid_session
        assigns(:autore).should be_a(Autore)
        assigns(:autore).should be_persisted
      end

      it "redirects to the created autore" do
        post :create, {:autore => valid_attributes}, valid_session
        response.should redirect_to(Autore.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved autore as @autore" do
        # Trigger the behavior that occurs when invalid params are submitted
        Autore.any_instance.stub(:save).and_return(false)
        post :create, {:autore => { "nome" => "invalid value" }}, valid_session
        assigns(:autore).should be_a_new(Autore)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Autore.any_instance.stub(:save).and_return(false)
        post :create, {:autore => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested autore" do
        autore = Autore.create! valid_attributes
        # Assuming there are no other autores in the database, this
        # specifies that the Autore created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Autore.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => autore.to_param, :autore => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested autore as @autore" do
        autore = Autore.create! valid_attributes
        put :update, {:id => autore.to_param, :autore => valid_attributes}, valid_session
        assigns(:autore).should eq(autore)
      end

      it "redirects to the autore" do
        autore = Autore.create! valid_attributes
        put :update, {:id => autore.to_param, :autore => valid_attributes}, valid_session
        response.should redirect_to(autore)
      end
    end

    describe "with invalid params" do
      it "assigns the autore as @autore" do
        autore = Autore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Autore.any_instance.stub(:save).and_return(false)
        put :update, {:id => autore.to_param, :autore => { "nome" => "invalid value" }}, valid_session
        assigns(:autore).should eq(autore)
      end

      it "re-renders the 'edit' template" do
        autore = Autore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Autore.any_instance.stub(:save).and_return(false)
        put :update, {:id => autore.to_param, :autore => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested autore" do
      autore = Autore.create! valid_attributes
      expect {
        delete :destroy, {:id => autore.to_param}, valid_session
      }.to change(Autore, :count).by(-1)
    end

    it "redirects to the autores list" do
      autore = Autore.create! valid_attributes
      delete :destroy, {:id => autore.to_param}, valid_session
      response.should redirect_to(autores_url)
    end
  end

end
